language: go
go:
 - 1.8.x
services:
 - docker
env:
 global:
  - secure: IlBnOfg4pq7V4Iv94luQ3Wk5mTvfVinZX0QNhoJ4vyBAZFBsWPq1nvMDpscf41D6UOHOYJa6vWlacm+n0ZRJXiYGwpbNtB7JqC63W4/KnjEl8RCMsY1YshQyEYN7vm/UqcITDdIxLW7IkflCdhtH448EptvwVkGZQZIC9s/Qf5OYBdjeYX3+WJd2hGmOjOf+J8smdycYXL1S05frONQK3uh36mf9CQqC72xicTfxVWH7K9JTncpy4bdh06Zjl1Y74lWLyLOsWlwXMbF7QKUEW/0CRxMVAHzcu9e6CcFRrkRq+JERWaCXgrw4cUGUguvcXNl/WvirIxxPieolui2yjy2fehSNCTFTWiFGZZzdtG/DmCHNtdUoFUjrdYQyRNvf2yxi3PtZNomPK2M7YimMhj07HtfdEQqFJSwttZXbVoKBtSkHNLXYrNZgPUXDi0SJxLxu2F6MEnfAC6OXVPad461mmYLNvt61+IqBt1jS6FJjMAsx4ADZsK27nK635gnNp8wCpD7zdyeSQuoXvLkE+F6IyEHq8ZvRpiVCz5N6DP3uO4qpOPpodnmZmS9I45T20O7OwEDzd3eDSosPXLLW4A2sGhoxj+0pCkIxpZaEcbGc8k9Jd02AeC/+YSz0D5uNlrP3Wlcbeq8OR4JsuHtdGn9hstvepQ3a3UuMilYO6RE=
  - secure: CoU2ufeXJYz7DuWMoHbFJVkNF1cNGX/EMXN8ph3rf0V5iWd8cchrDtOPhCQdyeVQ5na5K1XybF5oQ5MFT2baItu1KbJZbfdg0bPyHW3W4XJXmtqnGIQdoDNI1C22+lkKp+clkETNoBO/mXubCcByy4GxG5gXoSOoRORU5wfp4GHnAJKB/wwuHvTwNe9KPenWpgseXIb3oKGpLh/FUR2JBHOYqVyez6PyIqpsgoWRm11nDqtq4V44AF8hBNBQGOZAV8I63WGhIFsAoUzMPtp4LeIQ4P8cshMozn1Tc4oQerNEHAtUI3veaawVcPqOUhCUImz9am0cBPTuFhpOUhTpdVIzVEjUG8APtykPq4ogz8FIPfnpLUsZZcg6KrgpVoB+VZWtMEX7l+3cEPm4VV9WyBOpy0w3evkQxnPPyzfLEzbsHREqgKFXdGetMIQci6DYPosdQkvg3b0b2UoCFFAMXOOuYmFgL84COYviGL3Waz6BvfZuwj/ZZBLkA5W8QdrVYx4369g7A9UuqphYWceFGZ569bwd2xMvaTDP6+j++6NTzEmA3Q70CGDcb/jJW7sMQX0W//2cTxWIIFtmGq659S1v2BI/hQHcOHCIGrJ8Z6W1Fw1Y2FluMmJOXP7CaDqcorALRDtE9ait3JjzQNBXVXbx52b26/LeRrQJOfcsa1I=
cache:
  directories:
  - $TRAVIS_BUILD_DIR/vendor
before_install:
 - curl https://glide.sh/get | sh
install: make install
script:
 - make test
 - go build
