language: go
go:
- 1.8.x
services:
- docker
env:
 - TRAVIS_GO_VERSION=1.8.3
cache:
  directories:
  - $TRAVIS_BUILD_DIR/vendor
before_install:
- curl https://glide.sh/get | sh
install: make install
script:
- make test
- go build
dd:
  secure: TlxbBEfPfY/0H43l8mvqu+ImyeYOhXFf8SOkjlwM+LcHctFXlIO+t1R67sDfGt9raNYguopbACi4bz32K0FxysLoXilQhuIM9fjvUxQ7F7N1fHzE9lYwzVkrpoAklyiTE9uT3bdoiVjf4P9SsNfnz9fmOVlkAJ+C68ejpOToUGR9flHaE38rZ9X7FFRGXzCWscZk7LqyppjzMhXFKIuxlTpzyWhM17uLxGG+DJi4gNH4LPEwjsp+XJwN+TpWjXnsp+td5xVy4vk/h67Ec6BuKuFKxHKJaDpkJyymVttFSGQj4DGWuvPHr7n5Cw+KmaKhK98fxijoFAYz9pOWi538FrWhIAvlR7kTl+i4nTGnyTEjooKcCqK5A6isdDO8b+6TIBV/ro3xfl7wjvFe4h+dzolOquya8IzUrB69ur3c6ARgqMTJ8F2VEOMkILJZU43lAt9dk8v4xr0NWyqLlzvzPjZznoPFwDv9ZDRLjUDeFhe7JFqU3DALqXsm1Rbtw7UzBuhA2NR2ePuqLV3bLE4RAB4iWdak8Vn5IV0gjWr3SU4PkCIWtj2odD11wHgD9Bmer/MspF5Nv4dY2C7KD0LAH6233Q3cZOy0ZJarZwZC1hcVHJQLXdKwSrblGjvRJ/QiKNKlAz9NxdLYToGLnHJb4YpyYxPjHatFfNDjDxQdGcI=
